import { FileText, FileCheck, FileEdit, Clock, Trash2 } from 'lucide-react';

export const postsKpis = [
  {
    id: 'total',
    title: 'Total Posts',
    value: '1,248',
    trend: '12.5%',
    isUp: true,
    sub: 'vs last 30 days',
    bgIcon: 'bg-rose-600 text-white shadow-sm',
    icon: FileText,
  },
  {
    id: 'published',
    title: 'Published',
    value: '986',
    trend: '15.2%',
    isUp: true,
    sub: 'vs last 30 days',
    bgIcon: 'bg-emerald-600 text-white shadow-sm',
    icon: FileCheck,
  },
  {
    id: 'draft',
    title: 'Draft',
    value: '156',
    trend: '3.4%',
    isUp: false,
    sub: 'vs last 30 days',
    bgIcon: 'bg-blue-600 text-white shadow-sm',
    icon: FileEdit,
  },
  {
    id: 'scheduled',
    title: 'Scheduled',
    value: '64',
    trend: '8.6%',
    isUp: true,
    sub: 'vs last 30 days',
    bgIcon: 'bg-amber-500 text-white shadow-sm',
    icon: Clock,
  },
  {
    id: 'trash',
    title: 'Trash',
    value: '42',
    trend: '2.1%',
    isUp: false,
    sub: 'vs last 30 days',
    bgIcon: 'bg-purple-600 text-white shadow-sm',
    icon: Trash2,
  },
];

export const tablePosts = [
  {
    id: 1,
    image: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=120&q=80',
    title: 'কলকাতায় ভারী বৃষ্টির পূর্বাভাস, আগামী ৪ দিন ভারী বৃষ্টি',
    author: 'Riya Saha',
    authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=80&q=80',
    authorType: 'img',
    category: 'রাজনীতি',
    categoryBg: 'bg-blue-600 text-white font-bold',
    status: 'Published',
    statusBg: 'bg-emerald-600 text-white font-bold',
    views: '12.4K',
    date: '20 Jun, 2024',
    time: '10:30 AM',
  },
  {
    id: 2,
    image: 'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?auto=format&fit=crop&w=120&q=80',
    title: 'লোকসভা ভোটের ফলাফল ২০২৪ : NDA এগিয়ে',
    author: 'Arindam Das',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=80&q=80',
    authorType: 'img',
    category: 'রাজনীতি',
    categoryBg: 'bg-blue-600 text-white font-bold',
    status: 'Published',
    statusBg: 'bg-emerald-600 text-white font-bold',
    views: '8.7K',
    date: '20 Jun, 2024',
    time: '09:15 AM',
  },
  {
    id: 3,
    image: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=120&q=80',
    title: 'টি-২০ বিশ্বকাপ : ভারতের দাপুটে জয়',
    author: 'Sports Desk',
    authorAvatar: '/images/logos/Nirbhik-Bangla-Icon.png',
    authorType: 'img',
    category: 'খেলা',
    categoryBg: 'bg-emerald-600 text-white font-bold',
    status: 'Published',
    statusBg: 'bg-emerald-600 text-white font-bold',
    views: '15.3K',
    date: '20 Jun, 2024',
    time: '08:45 AM',
  },
  {
    id: 4,
    image: 'https://images.unsplash.com/photo-1517976487492-5750f3195933?auto=format&fit=crop&w=120&q=80',
    title: 'ইসরোর নতুন স্যাটেলাইট সফল উৎক্ষেপণ',
    author: 'Tech Desk',
    authorInitials: 'T',
    authorAvatarBg: 'bg-blue-600 text-white',
    authorType: 'initial',
    category: 'বিজ্ঞান ও প্রযুক্তি',
    categoryBg: 'bg-purple-600 text-white font-bold',
    status: 'Scheduled',
    statusBg: 'bg-amber-500 text-white font-bold',
    views: '5.1K',
    date: '19 Jun, 2024',
    time: '11:20 AM',
  },
  {
    id: 5,
    image: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=120&q=80',
    title: 'নতুন সিনেমা মুক্তি পেল আজ সারাদেশে',
    author: 'Entertainment Desk',
    authorInitials: 'E',
    authorAvatarBg: 'bg-purple-600 text-white',
    authorType: 'initial',
    category: 'বিনোদন',
    categoryBg: 'bg-pink-600 text-white font-bold',
    status: 'Draft',
    statusBg: 'bg-slate-600 text-white font-bold',
    views: '2.3K',
    date: '19 Jun, 2024',
    time: '08:10 PM',
  },
  {
    id: 6,
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=120&q=80',
    title: 'বিশ্বনাথ অভিযানের LIVE আপডেট',
    author: 'Reporter Team',
    authorInitials: 'R',
    authorAvatarBg: 'bg-slate-700 text-white',
    authorType: 'initial',
    category: 'দেশ',
    categoryBg: 'bg-teal-600 text-white font-bold',
    status: 'Published',
    statusBg: 'bg-emerald-600 text-white font-bold',
    views: '3.8K',
    date: '19 Jun, 2024',
    time: '07:25 PM',
  },
  {
    id: 7,
    image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=120&q=80',
    title: 'শেয়ার বাজারে বড় পতন, সেনসেক্স নেমে গেল',
    author: 'Business Desk',
    authorInitials: 'B',
    authorAvatarBg: 'bg-amber-500 text-white',
    authorType: 'initial',
    category: 'অর্থনীতি',
    categoryBg: 'bg-orange-600 text-white font-bold',
    status: 'Published',
    statusBg: 'bg-emerald-600 text-white font-bold',
    views: '6.2K',
    date: '19 Jun, 2024',
    time: '06:40 PM',
  },
];
